#!/usr/bin/env python3

# Created by: Adam Diwani
# Created on: December 13, 2020
# This program tells users if a year is a leap year or not


def main():

    # Input
    leap_year_string = input("Enter a year: ")

    # Process
    try:
        leap_year = int(leap_year_string)

        if leap_year % 4 == 0:
            if leap_year % 100 != 0:
                # Output
                print("This is a leap year.")
            else:
                if leap_year % 400 == 0:
                    # Output
                    print("This is a leap year.")
                else:
                    # Output
                    print("This is not a leap year.")
        else:
            # Output
                print("This is not a leap year.")
    except Exception:
        # Output
        print("This year is not valid.")


if __name__ == "__main__":
    main()
